apiVersion: v1
kind: Service
metadata:
  labels:
    app: eda-producer-ms-ep
  name: eda-producer-ms-ep-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: eda-producer-ms-ep