apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: userXX-devexp-topic
  labels:
    strimzi.io/cluster: crdb-cluster
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 1
  replicas: 3
  topicName: userXX-devexp-topic